backend:
  name: github
  repo: username/repo-name
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "social"
    label: "لینک‌های اجتماعی"
    folder: "social"
    create: true
    slug: "social"
    fields:
      - {label: "متن اصلی", name: "main_text", widget: "text"}
      - {label: "اینستاگرام", name: "instagram", widget: "string"}
      - {label: "تلگرام", name: "telegram", widget: "string"}
      - {label: "یوتیوب", name: "youtube", widget: "string"}
