backend:
  name: github
  repo: heyat-fatemion/My_Link
  branch: main
  client_id: Ov23liVIs6RB42oiFg16
  client_secret: 93dbba5cd1079d5a5eaf30c767adff3255a74f39
media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "social"
    label: "لینک‌های اجتماعی"
    folder: "social"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "متن اصلی", name: "main_text", widget: "text" }
      - { label: "اینستاگرام", name: "instagram", widget: "string" }
      - { label: "تلگرام", name: "telegram", widget: "string" }
      - { label: "یوتیوب", name: "youtube", widget: "string" }
